/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

public class test12 extends Exception {
    private String Teks;
    test12(String s)
    {
        Teks="Excaption generated by: "+s;
        System.out.println(Teks);
    }
}
class Eksepsi {
    static void tampil(String s) throws Exception
    {
        System.out.println("Tampil");
        if(s.equals("Faishal"))
        {
            throw new test12(s);
        }
        System.out.println("OK!");
    }
    public static void main(String[] args) throws Exception {
        try
        {
            tampil("asep");
            tampil("faishal");
        }
        catch(test12 ex)
        {
            System.out.println("Tangkap: "+ex);
        }
    }
}